# Generated by Django 5.0.2 on 2024-02-28 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelance_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photo',
            new_name='Freelancer_Photo',
        ),
    ]
